### ISSUE TITLE
CMD + Z issue with Paddy 2 enabled.

### ISSUE THREAD

**Issue by cspadazzi** [DWilliames/paddy2-beta#37]
Hey man, love the work on this.
I haven't seen anyone else mention this, but I've noticed when I have paddy 2 enabled. My CMD+Z can sometimes become seriously buggy. I've narrowed it down to an issue with Paddy 2, when I disable it, the problem goes away completely.

From time to time using CMD+Z with paddy enabled can cause my document to a point way earlier.
As an added bonus, it seems when you try and "redo" from that point, Sketch crashes.

Let me know if you need some more information.
Running on Sketch 49.3.

**Comment by DWilliames** [comment]
Thanks @cspadazzi. I can't seem to replicate the issue.
I understand what you mean though.

Are you able to do a screen-recording or something with Quicktime so I can understand the exact scenario? Also, when Sketch does crash after doing 'Redo'; could you grab a copy of the crash log?

Also, just curious; do you have Paddy 1, or Anima Toolkit enabled? Because they won't play nice with Paddy 2.

**Comment by DWilliames** [comment]
Hey @cspadazzi – since I didn't hear back from you and I haven't heard this issue from others, I'm going to close this issue on Github for now.

If you do find the issue again, please re-open this issue. 👍
