### ISSUE TITLE
Reset action isn’t clear what it does

### ISSUE THREAD

**Issue by KevinGutowski** [DWilliames/paddy2-beta#41]
For some reason I thought it would just reset the plugin or something and not the whole application. Ideally there would be a warning if there was unsaved work but I think just being more explicit with the name of the action such as, “Restart Sketch” would be good enough for now.

![screen shot 2018-06-15 at 6 51 44 pm](https://user-images.githubusercontent.com/4199296/41494764-2cca8c22-70cd-11e8-98ec-bbd3a0290295.png)

**Comment by aparajita** [comment]
There is no such thing as unsaved work in Sketch. When you quit and restart the document is restored to the edited state it was in.

**Comment by KevinGutowski** [comment]
@aparajita I have that functionality turned off. Regardless of whether there is unsaved data, I think it would be useful to have the language more clear.

![screen shot 2018-06-17 at 10 25 55 am](https://user-images.githubusercontent.com/4199296/41510399-d9852e9e-7218-11e8-98b0-2c4c0761b240.png)

Check out this article for more details why: https://medium.com/@thomasdegry/how-sketch-took-over-200gb-of-our-macbooks-cb7dd10c8163

**Comment by aparajita** [comment]
Did you actually have a problem with revisions eating up too much space? Mine is only 5.9GB.

In any case, I agree that the language in the menu should be clearer.

**Comment by DWilliames** [comment]
Yeah; this action was purely for debugging purposes. 
I didn't intend to have it in the release, or make it understandable :P 

I use it for testing restarting Sketch + re-opening the same documents again — which is a command that happens after updating Paddy 2. Because, in order to get the changes for Paddy 2; you need to restart Sketch. 

My bad though. I'll take it out of the menu for releasing.
