### ISSUE TITLE
Multi-line text overrides doesn’t quite work

### ISSUE THREAD

**Issue by KevinGutowski** [DWilliames/paddy2-beta#46]
If I have a button with multiple lines and specify a padding around the text element it works just fine. However, once I make the group a symbol and attempt to use overrides, the padding isn’t quite what is expected.

## Steps to reproduce
1. Create a text layer with a fixed with.
2. Add some text to take up a few lines.
3. Add a rectangle for the background
4. Group these objects together
5. Specify padding on the rectangle background
6. Edit text and observe how rectangle is properly resized when text is one, two, or three lines.

7. Make the group you just created a symbol
8. Use the text override and observe how rectangle isn’t being resized properly when text is one, two, or three lines.

I’m not entirely sure if this is just a “bug” with Paddy or just Sketch Overrides not behaving as I expected.

**Comment by pixtur** [comment]
I noticed the same problem. Here is a quick example scene https://www.dropbox.com/s/8ilak42sowy9maq/multiline-text-problem.sketch?dl=0 
If this would work, it would be super useful.

**Comment by DWilliames** [comment]
Thanks @KevinGutowski.
I think I understand what you mean — which I think is slightly different to the case @pixtur has described.

 Here's the example I mocked up from your description:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6570446/42987128-84e91278-8c3b-11e8-9720-fe415a74b33d.png">

If this is was you meant; you are correct, the spacing doesn't look right; and that's because of the constraints set. You need to set the resizing constraints on the text layer to be all directions, and that will fix it.... like so:
![2018-07-20 16 41 51](https://user-images.githubusercontent.com/6570446/42987251-e6ee9d80-8c3b-11e8-9e70-65595aa0c8fe.gif)

---

@pixtur to your example; I would consider that a separate issue; that I'm working on 👍

**Comment by KevinGutowski** [comment]
Thanks a bunch! I dunno what I was thinking. Setting those constraints is exactly what I was looking for!

**Comment by DWilliames** [comment]
Awesome. It's a tricky one; because I'm sure people would miss setting those constraints all the time; I know I do.  🤔
