### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by ajilderda** [DWilliames/paddy2-beta#49]
Hi David, 

Great job on Paddy 2 thus far. Maybe a silly question, but is there a way others can contribute to this project? As far as I can see there are only compiled files.

Ciao!

**Comment by DWilliames** [comment]
Hey @ajilderda.

Really great question!

Right now I have my source files in a separate private repo; but I think I should definitely open it up for others to see and contribute to. However, I think there's a couple of things I need to do first:

* Make sure it can be run stand-alone. At the moment there's dependencies on files I have locally
* Write some basic instructions to get it running locally (since it's a Cocoa Framework)
* Clean up some of the structure in the code to hopefully make it somewhat readable
* Get over my fear of sharing possibly poorly written code 😅

I'll try and jump on this soon.
I've really dropped the ball recently on working on Paddy 2 — I'm going to try and focus on it a lot more again now. :)

**Comment by ajilderda** [comment]
Ah, that's great to hear David! Not sure if I'm able to help you with Cocoa, since I only have experience with Sketch's Javascript API. But I will definitely take a peek. 

Your plugin is so incredibly useful, I can imagine others would love to get involved. Have you considered looking for maintainers/contributors?

**Comment by salux** [comment]
Slightly different take on contributing... unfortunately, I have nothing to offer from a technical perspective if you're in Cocoa, but I'd gladly contribute $ if it helped get the rest of the feature done faster! Sending you $5 is one thing, but I have a feeling the community you've served would be more than happy to serve you back if it helped.
