### ISSUE TITLE
[Feature request] Stacking: stretch option

### ISSUE THREAD

**Issue by aparajita** [DWilliames/paddy2-beta#5]
I didn't see this on your list. One alignment feature Anima has with stacks is the ability to stretch all views to match the width/height of the widest/tallest layer. This would be useful to have.

Currently there isn't room for another alignment icon, so a solution would be to only show the alignment options relevant to the current orientation (horizontal or vertical), which would leave space for another alignment icon. This would be better UX in any case.

**Comment by DWilliames** [comment]
Thanks for the idea @aparajita. I'm sorry, are you able to elaborate on it a bit more; I don't fully understand how it works. And I can't seem to find any mention of it in Anima's documentation.

At the moment I disable the ineligible alignment icons; so you're right, I could definitely show a different icon in their place. I'm just not sure what that icon would do.

Would you mind do a quick screen recording or something with Quicktime to demonstrate the behaviour? That would be extremely helpful. 🤗

**Comment by aparajita** [comment]
Pablo Stanley talks about the fill alignment option here: https://youtu.be/DiCXg17CwIY?t=278

Icons Anima uses:

![image](https://user-images.githubusercontent.com/22218/39824666-c110bc20-5364-11e8-844c-9a92b3aac71d.png)

When alignment is changed from vertical to horizontal, the four alignment icons change correspondingly.

**Comment by nvenk** [comment]
**+1**. First off, thanks for the amazing work @DWilliames!! Paddy is saving me SO MUCH time at work. 

I believe stretch would be a really useful feature too. I'm creating a dropdown list right now, and each list item is a different width. Right now, the background stretches to fit the largest one.

![image](https://user-images.githubusercontent.com/10296649/39949326-0d8b1ef8-552f-11e8-997b-449757d2ddf1.png)

It would be great to have a stretch option (maybe a `[hs]` or `[vs]` tag on the background layer, that would stretch the background to the width/height of the largest sibling? 

![image](https://user-images.githubusercontent.com/10296649/39949378-58181cd2-552f-11e8-844e-8a44f554a4eb.png)

In this case, I'd imagine `[hs]` would stretch the background to the width of the widest sibling.
since the parent group has an `[l]` on it, the contents would left align anyway.

I hope that made sense.

**Comment by DWilliames** [comment]
I understand now :)

Thanks for the clarification @aparajita and @nvenk. Definitely a great idea, I'll add it to the roadmap

**Comment by nvenk** [comment]
@Arroyodorado Yeah I thought about that, but my concern was that I don't want all the child layers to stretch to the width of the parent. By putting the [*s] parameter on the child, you have the control to stretch only the layers you want. 

For example, I have another use-case where I have a vertical accent bar that goes from top to bottom of its container. That's the only element that stretches, but it has a ton of sibling containers that have other elements, and don't need to be stretched.
