### ISSUE TITLE
[Bug] Props in layer names is broken & Groups as padding with no siblings is broken

### ISSUE THREAD

**Issue by richardsison** [DWilliames/paddy2-beta#55]
- [x] Stack and Padding Values cannot be set (or overridden) on the layer/group name anymore: https://d.pr/v/h0G9Ih
- [x] Activating Padding also shrinks the layers down. I don't even know what it's trying to do… Sometimes it even locks it to the top-left corner: https://d.pr/v/L59leB

I can't even workaround these bugs. Was there something wrong with the beta release? There's no way this could've been missed…

I've tried reinstalling Paddy 2, I don't have Paddy 1 or Anima installed. Using latest version of Sketch (51.1) and running High Sierra 10.13.6.

**Comment by highvoltaged** [comment]
Yes, this is what I found too

**Comment by DWilliames** [comment]
Oops. Yeah sorry @richardsison.
Good catch. I can re-produce.

Sorry... just one guy here chugging away here — turns out I'm not great at QA-ing it myself. Sorry.
You can download the previous versions from here: https://github.com/DWilliames/paddy2-beta/releases 

I started the work on 0.5 quite a while ago and stopped for quite a few weeks. 
I created the settings option for 'layer names', and whilst it seemed to be working when I did it. I must've broken it before I released 0.5

Sorry. I'll look into it now.

**Comment by DWilliames** [comment]
Alright, I've release v0.6 as a patch for this.
Let me know if it works for you 🤞

**Comment by richardsison** [comment]
All good mate! Thanks for getting on to it quick; you're a legend!

Found a small bug that when you set the padding on the layer list, it triggers in the inspector, but it's not activated by default.

I'll post it separately.

**Comment by DWilliames** [comment]
Thanks @richardsison. I'll close this issue for now 👍
